#############################################
#############################################
### MUTATION

type Mutation {
  addCustomer(customer: CustomerInput!): Customer
  addCustomers(customers: [CustomerInput]!): [Customer]
}
