type Mutation {
  addCustomer(customer: CustomerInput!): Customer
  updateCustomer(customer: CustomerInput!): Customer
  removeCustomer(customer: CustomerInput!): String
  truncateCustomers: String
  generateRandomCustomer: Customer
}
